# Generated by Django 5.1.1 on 2024-09-23 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='role',
            field=models.CharField(blank=True, choices=[('teacher', 'Teacher'), ('hr manager', 'Human Resource Manager'), ('librarian', 'Librarian'), ('finance manager', 'Finance Manager')], default=None, max_length=20, null=True),
        ),
    ]
