# Generated by Django 5.1.1 on 2024-10-19 19:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schooladminstration', '0007_institution_created_at'),
        ('teacher', '0003_rename_feedback_submission_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='assignment',
            name='school',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='schooladminstration.institution'),
        ),
        migrations.AddField(
            model_name='lessonplan',
            name='school',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lessonplans', to='schooladminstration.institution'),
        ),
    ]
