# Generated by Django 5.1.1 on 2024-10-19 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0004_assignment_created_at_assignment_school_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='assignment',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='student',
        ),
        migrations.DeleteModel(
            name='Assignment',
        ),
        migrations.DeleteModel(
            name='Submission',
        ),
    ]
