# Generated by Django 5.1 on 2024-08-25 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_permision', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permision',
            name='can_manage_employees',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='permision',
            name='can_manage_finances',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='permision',
            name='can_manage_library',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='permision',
            name='is_admin',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='permision',
            name='is_supper_admin',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
