# Generated by Django 5.1 on 2024-08-11 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
        ('finance', '0001_initial'),
        ('schooladminstration', '0001_initial'),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fee',
            old_name='amount_paid',
            new_name='fee_amount',
        ),
        migrations.RemoveField(
            model_name='fee',
            name='fully_paid',
        ),
        migrations.RemoveField(
            model_name='fee',
            name='student',
        ),
        migrations.RemoveField(
            model_name='fee',
            name='total_amount',
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='teacher',
        ),
        migrations.AddField(
            model_name='fee',
            name='school',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='schooladminstration.institution'),
        ),
        migrations.AddField(
            model_name='payroll',
            name='employee',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payroll', to='employee.employee'),
        ),
        migrations.AddField(
            model_name='payroll',
            name='payment_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='payroll',
            name='school',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payroll', to='schooladminstration.institution'),
        ),
        migrations.CreateModel(
            name='FeeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schooladminstration.institution')),
            ],
        ),
        migrations.AddField(
            model_name='fee',
            name='fee_category',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='finance.feecategory'),
        ),
        migrations.CreateModel(
            name='FeePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fully_paid', models.BooleanField(default=False)),
                ('fee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_payments', to='finance.fee')),
                ('school', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fee_payments', to='schooladminstration.institution')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_payments', to='student.student')),
            ],
        ),
        migrations.CreateModel(
            name='FeePaymentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateField(auto_now_add=True)),
                ('fee_payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_payments_history', to='finance.feepayment')),
                ('school', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fee_payments_history', to='schooladminstration.institution')),
            ],
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
