# Generated by Django 5.1 on 2024-08-11 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_rename_amount_paid_fee_fee_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='date_incurred',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
