# Generated by Django 5.1 on 2024-08-14 03:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_expense_date_alter_expense_date_incurred'),
        ('schooladminstration', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feepayment',
            name='fully_paid',
        ),
        migrations.AddField(
            model_name='feecategory',
            name='description',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='fee',
            name='fee_category',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fees', to='finance.feecategory'),
        ),
        migrations.AlterField(
            model_name='fee',
            name='school',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fees', to='schooladminstration.institution'),
        ),
        migrations.AlterField(
            model_name='feecategory',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_categories', to='schooladminstration.institution'),
        ),
    ]
