# Generated by Django 5.1 on 2024-08-14 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_remove_feecategory_students_feecategory_enrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='feepayment',
            name='payment_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
