# Generated by Django 5.1 on 2024-08-15 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_feepayment_payment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='fee',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
