# Generated by Django 5.1 on 2024-08-17 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_fee_fee_tittle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fee',
            old_name='fee_tittle',
            new_name='fee_title',
        ),
    ]
