# Generated by Django 5.1 on 2024-08-17 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0011_income'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fee',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='feepayment',
            options={'ordering': ['-payment_date']},
        ),
        migrations.AlterModelOptions(
            name='feepaymenthistory',
            options={'ordering': ['-payment_date']},
        ),
    ]
