# Generated by Django 5.1 on 2024-08-17 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0013_alter_expense_date_alter_income_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='income',
            options={'ordering': ['-date']},
        ),
    ]
