# Generated by Django 5.1 on 2024-08-17 22:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0014_alter_expense_options_alter_income_options'),
        ('school_calendar', '0005_alter_academicyear_options_term_closed'),
    ]

    operations = [
        migrations.AddField(
            model_name='feepayment',
            name='academic_year',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fees', to='school_calendar.academicyear'),
        ),
        migrations.AddField(
            model_name='feepayment',
            name='term',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fee_payments', to='school_calendar.term'),
        ),
    ]
