# Generated by Django 5.1 on 2024-08-18 00:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0015_feepayment_academic_year_feepayment_term'),
        ('school_calendar', '0005_alter_academicyear_options_term_closed'),
        ('schooladminstration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='academic_year',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='school_calendar.academicyear'),
        ),
        migrations.AddField(
            model_name='expense',
            name='term',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='school_calendar.term'),
        ),
        migrations.AddField(
            model_name='income',
            name='academic_year',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incomes', to='school_calendar.academicyear'),
        ),
        migrations.AddField(
            model_name='income',
            name='term',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incomes', to='school_calendar.term'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='schooladminstration.institution'),
        ),
        migrations.AlterField(
            model_name='income',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incomes', to='schooladminstration.institution'),
        ),
    ]
