# Generated by Django 5.1.1 on 2024-09-11 03:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_alter_attendancedate_date'),
        ('finance', '0018_payslip'),
        ('school_calendar', '0008_alter_academicyear_year'),
        ('schooladminstration', '0002_course_school_department_school_subject_school_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('bank transfer', 'Bank Transfer'), ('cheque', 'Cheque')], default=None, max_length=15, null=True),
        ),
        migrations.CreateModel(
            name='AdvancePayroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(blank=True, choices=[('cash', 'Cash'), ('bank transfer', 'Bank Transfer'), ('cheque', 'Cheque')], default=None, max_length=15, null=True)),
                ('payment_date', models.DateField(blank=True, default=None, null=True)),
                ('academic_year', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='advance_payroll', to='school_calendar.academicyear')),
                ('employee', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='advance_payroll', to='employee.employee')),
                ('school', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='advance_payroll', to='schooladminstration.institution')),
                ('term', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='advance_payroll', to='school_calendar.term')),
            ],
        ),
        migrations.CreateModel(
            name='DeductionAndAllowance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('allowances', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dedactions', models.DecimalField(decimal_places=2, max_digits=10)),
                ('academic_year', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deductions_a', to='school_calendar.academicyear')),
                ('employee', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deductions_a', to='employee.employee')),
                ('school', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deductions_a', to='schooladminstration.institution')),
                ('term', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deductions_a', to='school_calendar.term')),
            ],
        ),
    ]
