# Generated by Django 5.1.1 on 2024-09-11 04:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_alter_attendancedate_date'),
        ('finance', '0019_payroll_payment_method_advancepayroll_and_more'),
        ('school_calendar', '0008_alter_academicyear_year'),
        ('schooladminstration', '0002_course_school_department_school_subject_school_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollReconciliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('allowances', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True)),
                ('dedactions', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True)),
                ('processed', models.BooleanField(default=False)),
                ('academic_year', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deductions_a', to='school_calendar.academicyear')),
                ('employee', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deductions_a', to='employee.employee')),
                ('school', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deductions_a', to='schooladminstration.institution')),
                ('term', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deductions_a', to='school_calendar.term')),
            ],
        ),
        migrations.DeleteModel(
            name='DeductionAndAllowance',
        ),
    ]
