# Generated by Django 5.1.1 on 2024-10-12 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0010_alter_leaverequest_date_returned'),
        ('finance', '0020_payrollreconciliation_delete_deductionandallowance'),
        ('school_calendar', '0009_calendarevent'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='advancepayroll',
            unique_together={('month', 'employee', 'term')},
        ),
        migrations.AlterUniqueTogether(
            name='payroll',
            unique_together={('month', 'employee', 'term')},
        ),
        migrations.AlterUniqueTogether(
            name='payrollreconciliation',
            unique_together={('month', 'employee', 'term')},
        ),
    ]
