# Generated by Django 5.1.1 on 2024-10-20 23:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0022_fee_period_feepayment_fully_paid_otherfee_invoice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feepayment',
            name='fee',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fee_payments', to='finance.fee'),
        ),
    ]
