# Generated by Django 5.1.1 on 2024-10-20 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0023_alter_feepayment_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='discount_percentage',
            field=models.IntegerField(blank=True, default=None, max_length=2, null=True),
        ),
    ]
