# Generated by Django 5.1.1 on 2024-10-26 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0024_alter_invoice_discount_percentage'),
        ('school_calendar', '0009_calendarevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='fee',
            name='term',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fees', to='school_calendar.term'),
        ),
    ]
