# Generated by Django 5.1.1 on 2024-10-26 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0025_fee_term'),
        ('school_calendar', '0009_calendarevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='fee',
            name='academic_year',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fees', to='school_calendar.academicyear'),
        ),
        migrations.AlterField(
            model_name='feepayment',
            name='academic_year',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fee_payments', to='school_calendar.academicyear'),
        ),
        migrations.AlterUniqueTogether(
            name='fee',
            unique_together={('term',)},
        ),
    ]
