# Generated by Django 5.1.1 on 2024-10-26 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0026_fee_academic_year_alter_feepayment_academic_year_and_more'),
        ('school_calendar', '0009_calendarevent'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='fee',
            unique_together={('term', 'academic_year')},
        ),
    ]
