# Generated by Django 5.1.1 on 2024-09-17 04:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schooladminstration', '0004_delete_notice'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Free', 'Free - Limited Features'), ('Basic', 'Basic - Least Limited Features'), ('Premium', 'Premium - Full Features')], default='Free', max_length=50)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('duration', models.IntegerField(default=30)),
            ],
        ),
        migrations.CreateModel(
            name='SchoolSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('is_trial', models.BooleanField(default=False)),
                ('school', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='schooladminstration.institution')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_subscriptions', to='subscription.subscriptionplan')),
            ],
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.CharField(max_length=50)),
                ('plan', models.ManyToManyField(null=True, related_name='plan_features', to='subscription.subscriptionplan')),
            ],
        ),
    ]
