# Generated by Django 5.1.1 on 2024-09-20 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0004_subscriptionplan_yearly_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='description',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
