# Generated by Django 5.1.1 on 2024-11-18 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0006_subscriptionplan_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='half_year_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=9, null=True),
        ),
    ]
