# Generated by Django 5.1.1 on 2024-11-24 03:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schooladminstration', '0007_institution_created_at'),
        ('subscription', '0007_subscriptionplan_half_year_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='duration',
        ),
        migrations.CreateModel(
            name='SubscriptionPayments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(max_length=10)),
                ('trans_id', models.IntegerField(max_length=30)),
                ('duration', models.CharField(max_length=20)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_payments', to='schooladminstration.institution')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_payments', to='subscription.schoolsubscription')),
            ],
        ),
    ]
