# Generated by Django 5.1.1 on 2024-11-24 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0008_remove_subscriptionplan_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionpayments',
            name='successful',
            field=models.BooleanField(default=False),
        ),
    ]
