# Generated by Django 5.1.1 on 2024-11-24 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0009_subscriptionpayments_successful'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionpayments',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
