# Generated by Django 5.1.1 on 2024-11-24 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0010_alter_subscriptionpayments_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptionpayments',
            name='subscription',
        ),
    ]
