# Generated by Django 5.1 on 2024-09-08 12:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
        ('schooladminstration', '0002_course_school_department_school_subject_school_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='employment_status',
            field=models.CharField(blank=True, choices=[('FT', 'Full-Time'), ('PT', 'Part-Time'), ('CON', 'Contract'), ('SUB', 'Substitute')], default=None, max_length=3, null=True),
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('Identification Card', 'identification card'), ('Contract', 'contract'), ('Certification', 'certification'), ('Other', 'other')], max_length=100)),
                ('document', models.FileField(upload_to='documents/')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_documents', to='schooladminstration.institution')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('P', 'Present'), ('A', 'Absent'), ('L', 'Late')], max_length=10)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_attendance', to='schooladminstration.institution')),
            ],
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(choices=[('Sick', 'Sick'), ('Vacation', 'Vacation'), ('Personal', 'Personal')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Returned', 'Returned')], default='Approved', max_length=10)),
                ('date_returned', models.DateField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaves', to='schooladminstration.institution')),
            ],
        ),
    ]
