# Generated by Django 5.1.1 on 2024-09-10 03:11

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_alter_employee_date_of_birth'),
        ('schooladminstration', '0002_course_school_department_school_subject_school_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeattendance',
            name='status',
            field=models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late')], max_length=10),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='leave_type',
            field=models.CharField(choices=[('sick', 'Sick'), ('vacation', 'Vacation'), ('personal', 'Personal')], max_length=20),
        ),
        migrations.CreateModel(
            name='AttendanceDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_attendance_dates', to='schooladminstration.institution')),
            ],
        ),
        migrations.AddField(
            model_name='employeeattendance',
            name='attendance_date',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_attendance', to='employee.attendancedate'),
        ),
    ]
