# Generated by Django 5.1.1 on 2024-09-10 04:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_alter_employeeattendance_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancedate',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, unique=True),
        ),
    ]
