# Generated by Django 5.1.1 on 2024-09-11 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_alter_attendancedate_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeattendance',
            name='processed',
            field=models.BooleanField(default=False),
        ),
    ]
