# Generated by Django 5.1.1 on 2024-09-12 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0007_employeeattendance_processed'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='leave_status',
            field=models.CharField(choices=[('sick', 'Sick'), ('vacation', 'Vacation'), ('personal', 'Personal')], default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='leave_type',
            field=models.CharField(choices=[('paid', 'Paid'), ('unpaid', 'Unpaid')], max_length=20),
        ),
    ]
