# Generated by Django 5.1.1 on 2024-09-12 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0008_leaverequest_leave_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='processed',
            field=models.BooleanField(default=False),
        ),
    ]
