# Generated by Django 5.1.1 on 2024-09-12 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0009_leaverequest_processed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequest',
            name='date_returned',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
