# Generated by Django 5.1.1 on 2024-12-02 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0011_alter_document_document_alter_leaverequest_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='doc_type',
            field=models.CharField(choices=[('CV', 'Cv'), ('Identification Card', 'identification card'), ('Contract', 'contract'), ('Certification', 'certification'), ('Other', 'other')], max_length=100),
        ),
    ]
