# Generated by Django 5.1.1 on 2024-12-06 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0012_alter_document_doc_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='doc_type',
            field=models.CharField(choices=[('CV', 'cv'), ('Identification Card', 'identification card'), ('Contract', 'contract'), ('Certification', 'certification'), ('Other', 'other')], max_length=100),
        ),
    ]
