# Generated by Django 5.1.1 on 2024-12-06 03:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0004_alter_result_unique_together_alter_result_subject_and_more'),
        ('school_calendar', '0010_alter_academicyear_options_alter_term_options'),
        ('schooladminstration', '0011_alter_logo_logo'),
        ('student', '0002_alter_enrollment_courses_alter_enrollment_subjects'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_cards', to='school_calendar.academicyear')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_cards', to='exams.exam')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_cards', to='schooladminstration.institution')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_cards', to='student.student')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_cards', to='school_calendar.term')),
            ],
        ),
    ]
