# Generated by Django 5.1 on 2024-08-17 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_calendar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicyear',
            name='closed',
            field=models.BooleanField(default=False),
        ),
    ]
