# Generated by Django 5.1 on 2024-08-17 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_calendar', '0002_academicyear_closed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='academicyear',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='term',
            options={'ordering': ['-date']},
        ),
    ]
