# Generated by Django 5.1 on 2024-08-17 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_calendar', '0003_alter_academicyear_options_alter_term_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='academicyear',
            options={'ordering': ['date']},
        ),
    ]
