# Generated by Django 5.1 on 2024-08-18 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_calendar', '0005_alter_academicyear_options_term_closed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicyear',
            name='year',
            field=models.CharField(help_text='e.g 2024-2025', max_length=9),
        ),
    ]
