# Generated by Django 5.1 on 2024-08-19 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_calendar', '0006_alter_academicyear_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicyear',
            name='end_date',
            field=models.DateField(help_text='ending date of this academic year'),
        ),
        migrations.AlterField(
            model_name='academicyear',
            name='start_date',
            field=models.DateField(help_text='starting date of this academic year'),
        ),
        migrations.AlterField(
            model_name='academicyear',
            name='year',
            field=models.CharField(help_text='e.g 2024-2025 academic year', max_length=9),
        ),
        migrations.AlterField(
            model_name='term',
            name='end_date',
            field=models.DateField(help_text='ending date of this Term/Semister'),
        ),
        migrations.AlterField(
            model_name='term',
            name='start_date',
            field=models.DateField(help_text='starting date of this term/semister'),
        ),
        migrations.AlterField(
            model_name='term',
            name='title',
            field=models.CharField(help_text='e.g Term 1/Semister 2', max_length=50),
        ),
    ]
