# Generated by Django 5.1.1 on 2024-11-17 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_calendar', '0009_calendarevent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='academicyear',
            options={},
        ),
        migrations.AlterModelOptions(
            name='term',
            options={},
        ),
    ]
