# Generated by Django 5.1.1 on 2024-10-13 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0002_chat_message_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='show_onpage',
            field=models.BooleanField(default=False),
        ),
    ]
