# Generated by Django 5.1.1 on 2024-10-13 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0003_chat_show_onpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='udated_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
