# Generated by Django 5.1.1 on 2024-10-17 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0004_chat_udated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='show_onpage',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='DateStamp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('messages', models.ManyToManyField(related_name='date_messages', to='chatapp.message')),
            ],
        ),
    ]
