# Generated by Django 5.1.1 on 2024-10-17 05:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0005_alter_chat_show_onpage_datestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='datestamp',
            name='chat',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='date_messages', to='chatapp.chat'),
        ),
    ]
