# Generated by Django 5.1.1 on 2024-11-30 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parent', '0003_parent_full_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parent',
            name='full_name',
        ),
    ]
