# Generated by Django 5.1.1 on 2024-11-30 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parent', '0004_remove_parent_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='full_name',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
