# Generated by Django 5.1.1 on 2024-11-30 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parent', '0005_parent_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='title',
            field=models.CharField(blank=True, choices=[('Mr', 'Mr'), ('Mrs', 'Mrs'), ('Dr', 'Dr')], default=None, max_length=50, null=True),
        ),
    ]
