# Generated by Django 5.1.1 on 2024-11-30 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parent', '0007_rename_full_name_parent_first_name_parent_last_name_and_more'),
        ('student', '0002_alter_enrollment_courses_alter_enrollment_subjects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parentdetails',
            name='children',
        ),
        migrations.AddField(
            model_name='parentdetails',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_details', to='student.student'),
        ),
    ]
