# Generated by Django 5.1.1 on 2024-10-19 23:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0001_initial'),
        ('classroom', '0004_alter_classroom_unique_together'),
        ('schooladminstration', '0007_institution_created_at'),
        ('student', '0002_alter_enrollment_courses_alter_enrollment_subjects'),
        ('teacher', '0005_remove_submission_assignment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='teacher.instructor'),
        ),
        migrations.CreateModel(
            name='ClassWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateField(auto_now_add=True)),
                ('number_of_questions', models.IntegerField(blank=True, null=True)),
                ('classi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_works', to='classroom.classroom')),
                ('course', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='schooladminstration.course')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_works', to='schooladminstration.institution')),
                ('subject', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='schooladminstration.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_works', to='teacher.instructor')),
            ],
        ),
        migrations.CreateModel(
            name='ClassWorkResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('marks', models.IntegerField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('class_work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='assignments.classwork')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='student.student')),
            ],
        ),
    ]
