# Generated by Django 5.1.1 on 2024-10-19 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0002_alter_assignment_teacher_classwork_classworkresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='title',
            field=models.CharField(choices=[('mid exams', 'Mid Exams'), ('assignment', 'Assignment/home work'), ('class work', 'Class Work')], max_length=50),
        ),
    ]
