# Generated by Django 5.1.1 on 2024-10-19 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0003_alter_assignment_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classwork',
            name='title',
        ),
        migrations.AlterField(
            model_name='assignment',
            name='title',
            field=models.CharField(choices=[('test', 'Test/Mid Exams'), ('assignment', 'Assignment/home work')], max_length=50),
        ),
    ]
