# Generated by Django 5.1.1 on 2024-10-13 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0003_alter_classroom_options'),
        ('schooladminstration', '0007_institution_created_at'),
        ('teacher', '0002_alter_instructor_role'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='classroom',
            unique_together={('teacher_assigned', 'school')},
        ),
    ]
