# Generated by Django 5.1.1 on 2024-09-14 02:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schooladminstration', '0002_course_school_department_school_subject_school_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='id',
            field=models.CharField(blank=True, default=uuid.uuid4, max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
