# Generated by Django 5.1.1 on 2024-09-17 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schooladminstration', '0003_alter_institution_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notice',
        ),
    ]
