# Generated by Django 5.1.1 on 2024-09-21 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schooladminstration', '0004_delete_notice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='edu_offer',
            field=models.CharField(choices=[('primary education', 'Primary Education'), ('secondary education', 'Secondary Education'), ('tertialy education', 'Tertiary Education')], max_length=20),
        ),
    ]
