# Generated by Django 5.1.1 on 2024-10-10 07:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schooladminstration', '0006_institution_tried_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='created_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
