# Generated by Django 5.1.1 on 2024-12-01 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schooladminstration', '0008_schooladdress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schooladdress',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_details', to='schooladminstration.institution'),
        ),
    ]
