# Generated by Django 5.1.1 on 2024-12-02 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schooladminstration', '0010_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logo',
            name='logo',
            field=models.ImageField(upload_to='school_files/logo'),
        ),
    ]
