# Generated by Django 5.1 on 2024-08-26 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0003_alter_classroom_options'),
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetable',
            name='classi',
        ),
        migrations.AddField(
            model_name='timetable',
            name='classes',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='timetable', to='classroom.classroom'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='title',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
