# Generated by Django 5.1.1 on 2024-09-26 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_admin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemfeature',
            name='description',
        ),
        migrations.AddField(
            model_name='systemfeature',
            name='description1',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='systemfeature',
            name='description2',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='systemfeature',
            name='description3',
            field=models.TextField(default=None),
        ),
    ]
