# Generated by Django 5.1.1 on 2024-10-13 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_admin', '0003_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content1', models.TextField()),
                ('content2', models.TextField()),
                ('vision', models.TextField()),
                ('mission', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
