# Generated by Django 5.1.1 on 2024-10-21 03:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_alter_usernotification_recipient'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='sender',
        ),
        migrations.AddField(
            model_name='notification',
            name='i_d',
            field=models.IntegerField(blank=True, default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='is_user_notif',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='read_recipients',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='read_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notification',
            name='recipients',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='unread_notifications', to=settings.AUTH_USER_MODEL),
        ),
    ]
