# Generated by Django 5.1.1 on 2024-10-21 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_remove_notification_read_recipients_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='show_onpage',
            field=models.BooleanField(default=True),
        ),
    ]
